=== JordanKornel/DWWUAP_XMLGyak/DWWUAP_XML_Féléves_Feladat/1. feladat/XMLSchemaDWWUAP.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<!-- Adatok típusai-->

<xs:element name="telef_szam" type="xs:integer" />
<xs:element name="Email" type="xs:string" />
<xs:element name="V_nev" type="xs:string" />
<xs:element name="K_nev" type="xs:string" />
<xs:element name="elert_pont" type="xs:integer" />
<xs:element name="kor" type="xs:integer" />
<xs:element name="telekhely" type="xs:string" />
<xs:element name="alapitas_eve" type="xs:integer" />
<xs:element name="e_nev" type="xs:string" />
<xs:element name="I_szam" type="xs:integer" />
<xs:element name="utca" type="xs:string" />
<xs:element name="hazszam" type="xs:integer" />
<xs:element name="gyakorlat" type="xs:string" />
<xs:element name="szobeli_kerdes" type="xs:string" />
<xs:element name="irasbeli" type="xs:string" />
<xs:element name="datum" type="xs:string" />


<xs:attribute name="V_F_F" type="xs:string" />
<xs:attribute name="V_F_V" type="xs:string" />
<xs:attribute name="V_ID" type="xs:integer" />
<xs:attribute name="vadasz-egyesulet" type="xs:string" />
<xs:attribute name="E_ID" type="xs:integer" />
<xs:attribute name="vadasz-felugyelo" type="xs:integer" />
<xs:attribute name="F_ID" type="xs:integer" />
<xs:attribute name="felugyelo-vizsga" type="xs:integer" />
<xs:attribute name="vizsga_ID" type="xs:integer" />
<xs:attribute name="Vi_Va_Vi" type="xs:integer" />
<xs:attribute name="Va_Vi_Va" type="xs:integer" />

<!-- Komplex típusok-->

    <xs:complexType name="vadaszTipus">
        <xs:sequence>
            <xs:element ref="telef_szam"/>
            <xs:element ref="Email"/>
            <xs:element ref="V_nev"/>
            <xs:element ref="K_nev"/>
            <xs:element ref="elert_pont"/>
            <xs:element ref="kor"/>
        </xs:sequence>
        <xs:attribute ref="V_ID" use="required"/>
        <xs:attribute ref="vadasz-egyesulet" use="required"/>
    </xs:complexType>

    <xs:complexType name="egyesuletTipus">
        <xs:sequence>
            <xs:element ref="telekhely"/>
            <xs:element ref="alapitas_eve"/>
            <xs:element ref="e_nev"/>
        </xs:sequence>
        <xs:attribute ref="vadasz-felugyelo" use="required"/>
        <xs:attribute ref="E_ID" use="required"/>
    </xs:complexType>

    <xs:complexType name="felugyeloTipus">
        <xs:sequence>
            <xs:element ref="V_nev"/>
            <xs:element ref="K_nev"/>
            <xs:element ref="Email"/>
            <xs:element ref="telef_szam"/>
        </xs:sequence>
        <xs:attribute ref="felugyelo-vizsga" use="required"/>
        <xs:attribute ref="F_ID" use="required"/>
    </xs:complexType>

    <xs:complexType name="vizsgaTipus">
        <xs:sequence>
            <xs:element ref="I_szam"/>
            <xs:element ref="utca"/>
            <xs:element ref="hazszam"/>
            <xs:element ref="gyakorlat"/>
            <xs:element ref="szobeli_kerdes"/>
            <xs:element ref="irasbeli"/>
        </xs:sequence>
        <xs:attribute ref="vizsga_ID" use="required"/>
    </xs:complexType>

    <xs:complexType name="vizsgaljaTipus">
        <xs:sequence>
            <xs:element ref="datum"/>
        </xs:sequence>
        <xs:attribute ref="Vi_Va_Vi" use="required"/>
        <xs:attribute ref="Va_Vi_Va" use="required"/>
    </xs:complexType>
    <xs:complexType name="felugyeliTipus">
        <xs:attribute ref="V_F_F" use="required"/>
        <xs:attribute ref="V_F_V" use="required"/>
    </xs:complexType>

<xs:element name="vadaszvizsga">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="vadasz" type="vadaszTipus" maxOccurs="unbounded" />
            <xs:element name="egyesulet" type="egyesuletTipus" maxOccurs="unbounded" />
            <xs:element name="felugyelo" type="felugyeloTipus" maxOccurs="unbounded" />
            <xs:element name="vizsga" type="vizsgaTipus" maxOccurs="unbounded" />
            <xs:element name="vizsgalja" type="vizsgaljaTipus" maxOccurs="unbounded" />
            <xs:element name="felugyeli" type="felugyeliTipus" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>


<!-- Kulcsok -->

    <xs:key name="Vadasz_kulcs">
        <xs:selector xpath="vadasz" />
        <xs:field xpath="@V_ID" />
    </xs:key>

    <xs:key name="egyesulet_kulcs">
        <xs:selector xpath="egyesulet" />
        <xs:field xpath="@E_ID" />
    </xs:key>

    <xs:key name="felugyelo_kulcs">
        <xs:selector xpath="felugyelo" />
        <xs:field xpath="@F_ID" />
    </xs:key>

    <xs:key name="vizsga_kulcs">
        <xs:selector xpath="vizsga" />
        <xs:field xpath="@vizsga_ID" />
    </xs:key>

    <!-- Idegen kulcsok-->

    <xs:keyref refer="Vadasz_kulcs" name="vadasz_idegen_kulcs">
        <xs:selector xpath="egyesulet" />
        <xs:field xpath="@vadasz-egyesulet" />
    </xs:keyref>

    <xs:keyref refer="egyesulet_kulcs" name="vizsga_idegen_kulcs">
        <xs:selector xpath="felugyelo" />
        <xs:field xpath="@vadasz-felugyelo" />
    </xs:keyref>

    <xs:keyref refer="felugyelo_kulcs" name="vizsga2_idegen_kulcs">
        <xs:selector xpath="felugyeli" />
        <xs:field xpath="@felugyelo-vizsga" />
    </xs:keyref>

    <xs:keyref refer="felugyelo_kulcs" name="vizsga3_idegen_kulcs">
        <xs:selector xpath="vizsga" />
        <xs:field xpath="@Vi_Va_Vi" />
    </xs:keyref>

    <xs:keyref refer="felugyelo_kulcs" name="vadasz2_idegen_kulcs">
        <xs:selector xpath="vadasz" />
        <xs:field xpath="@Va_Vi_Va" />
    </xs:keyref>

    <xs:keyref refer="felugyelo_kulcs" name="felugyelo_idegen_kulcs">
        <xs:selector xpath="felugyelo" />
        <xs:field xpath="@V_F_F" />
    </xs:keyref>

    <xs:keyref refer="vizsga_kulcs" name="vadasz3_idegen_kulcs">
        <xs:selector xpath="vadasz" />
        <xs:field xpath="@V_F_V" />
    </xs:keyref>


</xs:element>

</xs:schema>

=== JordanKornel/DWWUAP_XMLGyak/DWWUAP_XML_Féléves_Feladat/XMLDWWUAP.xml
<?xml version="1.0" encoding="UTF-8"?>

<vadaszvizsga xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchemaDWWUAP.xsd">

<vadasz vadasz-egyesulet="ve1" V_ID="1">
    <telef_szam>06202222222</telef_szam>
    <Email>valami@Email.com</Email>
    <V_nev>Kiss</V_nev>
    <K_nev>Pista</K_nev>
    <elert_pont>5</elert_pont>
    <kor>30</kor>
</vadasz>    

<vadasz vadasz-egyesulet="ve2" V_ID="2">
    <telef_szam>06202222223</telef_szam>
    <Email>valami2@Email.com</Email>
    <V_nev>Nagy</V_nev>
    <K_nev>Pista</K_nev>
    <elert_pont>6</elert_pont>
    <kor>40</kor>
</vadasz>    

<vadasz vadasz-egyesulet="ve3" V_ID="3">
    <telef_szam>06202222224</telef_szam>
    <Email>valam3@Email.com</Email>
        <V_nev>Valamilyen</V_nev>
        <K_nev>Pista</K_nev>
    <elert_pont>7</elert_pont>
    <kor>50</kor>
</vadasz>    

<egyesulet E_ID="1" vadasz-felugyelo="1">
    <telekhely>Miskolc</telekhely>
    <alapitas_eve>1969</alapitas_eve>
    <e_nev>Kis Egyesület</e_nev>
</egyesulet>

<egyesulet E_ID="2" vadasz-felugyelo="2">
    <telekhely>Pest</telekhely>
    <alapitas_eve>1980</alapitas_eve>
    <e_nev>Nagy Egyesület</e_nev>
</egyesulet>

<egyesulet E_ID="3" vadasz-felugyelo="3">
    <telekhely>Debrecen</telekhely>
    <alapitas_eve>1990</alapitas_eve>
    <e_nev>Gyors Egyesület</e_nev>
</egyesulet>

<felugyelo F_ID="1" felugyelo-vizsga="1">
    <V_nev>Kiss</V_nev>
    <K_nev>Lajos</K_nev>
    <Email>lajos@gmail.com</Email>
    <telef_szam>06203334444</telef_szam>
</felugyelo>

<felugyelo F_ID="2" felugyelo-vizsga="2">
    <V_nev>Nagy</V_nev>
    <K_nev>Lajos</K_nev>
    <Email>lajosanagy@gmail.com</Email>
    <telef_szam>06203334456</telef_szam>
</felugyelo>

<felugyelo F_ID="3" felugyelo-vizsga="3">
    <V_nev>Kiss</V_nev>
    <K_nev>Ferenc</K_nev>
    <Email>ferenc@gmail.com</Email>
    <telef_szam>06203338888</telef_szam>
</felugyelo>

<vizsga vizsga_ID="1">
    <I_szam>3666</I_szam>
    <utca>Petőfi</utca>
    <hazszam>1</hazszam>
    <gyakorlat>Kinti</gyakorlat>
    <szobeli_kerdes>Valami1</szobeli_kerdes>
    <irasbeli>Valami3</irasbeli>
</vizsga>

<vizsga vizsga_ID="2">
    <I_szam>3700</I_szam>
    <utca>Nagy</utca>
    <hazszam>7</hazszam>
    <gyakorlat>Kinti</gyakorlat>
    <szobeli_kerdes>Valami7</szobeli_kerdes>
    <irasbeli>Valami4</irasbeli>
</vizsga>

<vizsga vizsga_ID="3">
    <I_szam>3800</I_szam>
    <utca>Fekete</utca>
    <hazszam>30</hazszam>
    <gyakorlat>Kinti</gyakorlat>
    <szobeli_kerdes>Valami3</szobeli_kerdes>
    <irasbeli>Valami8</irasbeli>
</vizsga>

<vizsgalja Vi_Va_Vi="1" Va_Vi_Va="1">
<datum>2022.11.09.</datum>
</vizsgalja>

<vizsgalja Vi_Va_Vi="2" Va_Vi_Va="2">
    <datum>2022.11.16.</datum>
</vizsgalja>

<vizsgalja Vi_Va_Vi="3" Va_Vi_Va="3">
    <datum>2022.11.23.</datum>
</vizsgalja>

<felugyeli V_F_F="VFF1" V_F_V="VFV1"></felugyeli>
<felugyeli V_F_F="VFF2" V_F_V="VFV2"></felugyeli>
<felugyeli V_F_F="VFF3" V_F_V="VFV3"></felugyeli>

</vadaszvizsga>
