=== JordanKornel/DWWUAP_XMLGyak/DWWUAP_1005/JK_orarend.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="idTipus">
        <xs:restriction base="xs:string">
            <xs:minLength value="5" />
            <xs:maxLength value="10" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipusTipus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ElmÃ©let" />
            <xs:enumeration value="Gyakorlat" />
            <xs:enumeration value="Elm-Gyak" />
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="JK_orarend">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ora" maxOccurs="unbounded" >
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="targy" type="xs:string"/>
                            <xs:element name="idopont">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nap" type="xs:string"/>
                                        <xs:element name="tol" type="xs:string"/>
                                        <xs:element name="ig" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="helyszin" type="xs:string" />
                            <xs:element name="oktato" type="xs:string" />
                            <xs:element name="szak" type="xs:string" />
                        </xs:sequence>
                        <xs:attribute name="id" type="idTipus" use="required" />
                        <xs:attribute name="tipus" type="tipusTipus" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== JordanKornel/DWWUAP_XMLGyak/DWWUAP_1012/JK_orarend.xml
<?xml version="1.0" encoding="utf-8"?>

<!-- <!DOCTYPE JK_orarend SYSTEM "JK_orarend.dtd"> -->

<JK_orarend xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="JK_orarend.xsd">
    <ora id="GEIK-01" tipus="Elmélet">
        <targy>WEB Technológiák</targy>
        <idopont>
            <nap>Hétfő</nap>
            <tol>8:00</tol>
            <ig>10:00</ig>
        </idopont>
        <helyszin>XXX A1 III. em. 305</helyszin>
        <oktato>Agárdi Anita</oktato>
        <szak>Programtervező Informatikus</szak>
    </ora>

    <ora id="GEIK-02" tipus="Gyakorlat">
        <targy>WEB Technológiák</targy>
        <idopont>
            <nap>Hétfő</nap>
            <tol>16:00</tol>
            <ig>18:00</ig>
        </idopont>
        <helyszin>Inf 103</helyszin>
        <oktato>Agárdi Anita</oktato>
        <szak>Programtervező Informatikus</szak>
    </ora>

    <ora id="GEIK-03" tipus="Elmélet">
        <targy>Mesterséges Intelligencia Alapjai</targy>
        <idopont>
            <nap>Kedd</nap>
            <tol>9:00</tol>
            <ig>12:00</ig>
        </idopont>
        <helyszin>II A2 mfsz.</helyszin>
        <oktato>Kunné Dr. Tamás Judit</oktato>
        <szak>Programtervező Informatikus</szak>
    </ora>

    <ora id="GEIK-04" tipus="Gyakorlat">
        <targy>Mesterséges Intelligencia Alapjai</targy>
        <idopont>
            <nap>Szerda</nap>
            <tol>14:00</tol>
            <ig>15:00</ig>
        </idopont>
        <helyszin>Inf 15</helyszin>
        <oktato>Fazekas Levente</oktato>
        <szak>Programtervező Informatikus</szak>
    </ora>

    <ora id="GEIK-05" tipus="Elmélet">
        <targy>Adatkezelés XML-ben</targy>
        <idopont>
            <nap>Kedd</nap>
            <tol>12:00</tol>
            <ig>14:00</ig>
        </idopont>
        <helyszin>XXXII A1 magasfsz.</helyszin>
        <oktato>Dr. Bednarik László</oktato>
        <szak>Programtervező Informatikus</szak>
    </ora>

    <ora id="GEIK-06" tipus="Gyakorlat">
        <targy>Adatkezelés XML-ben</targy>
        <idopont>
            <nap>Szerda</nap>
            <tol>12:00</tol>
            <ig>14:00</ig>
        </idopont>
        <helyszin>Inf/101</helyszin>
        <oktato>Dr. Bednarik László</oktato>
        <szak>Programtervező Informatikus</szak>
    </ora>

    <ora id="GEIK-07" tipus="Elmélet">
        <targy>Algoritmusok és Vizsgálatuk</targy>
        <idopont>
            <nap>Kedd</nap>
            <tol>14:00</tol>
            <ig>18:00</ig>
        </idopont>
        <helyszin>X A1 II.em 218</helyszin>
        <oktato>Dr. Házy Attila</oktato>
        <szak>Programtervező Informatikus</szak>
    </ora>

    <ora id="GEIK-08" tipus="Elmélet">
        <targy>Vállalati Információs Rendszerek</targy>
        <idopont>
            <nap>Szerda</nap>
            <tol>16:00</tol>
            <ig>20:00</ig>
        </idopont>
        <helyszin>Inf 103</helyszin>
        <oktato>Dr. Sasvári Péter</oktato>
        <szak>Programtervező Informatikus</szak>
    </ora>

</JK_orarend>
